### ISSUE TITLE
Error adding a local or remote plugin 

### ISSUE THREAD

**Issue by esquil056l** [Acode-Foundation/Acode#1095]
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

No plugin has been added locally or remotely, it simply sends an alert saying that the plugin is invalid or that an error has occurred. I have even tried to add a plugin from a GitHub repository such as: https://github.com/Acode-Foundation/acode-plugin-python/tree/main or even the example: https://github.com/Acode-Foundation/acode-plugin/tree/main 

### Environment

I am using the most updated version of acode 1.10.6 and my Android version is 14, my cell phone model is a galaxy A04e 

### If applicable, attach your Acode.log file to this issue.

U

**Comment by bajrangCoder** [comment]
You can't add from plugin repo, As Acode accepts the url of plugin zip file
