### ISSUE TITLE
Error Fetching Plugins

### ISSUE THREAD

**Issue by M23jJohn** [Acode-Foundation/Acode#1101]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When i look for a plugin it says error

https://github.com/user-attachments/assets/dcf47f6c-1041-463f-a0a0-138920fb1904

### Environment

Android Version 14

### If applicable, attach your Acode.log file to this issue.

<details><summary>Acode.log</summary><pre>

</pre></details>

**Comment by sebastianjnuwu** [comment]
Still having trouble? Clear your cache and check your internet connection.

**Comment by M23jJohn** [comment]
I just knew whats causing it. Its happening because when a plugin is taking long to install I restart the app and when I'm back the bug is now showing

**Comment by bajrangCoder** [comment]
> I just knew whats causing it. Its happening because when a plugin is taking long to install I restart the app and when I'm back the bug is now showing

Got it , it's actually due to incomplete installation of any plugin.

Soon it will be patched.
