### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [Acode-Foundation/Acode#747]
Please support the Android 13 Themed App Icons feature.

![Screenshot_2023-07-06-12-10-04-349_de.mm20.launcher2.release.jpg](https://github.com/deadlyjack/Acode/assets/23485114/1c79d079-376e-41a7-9554-fcdaa8b13619)

**Comment by deadlyjack** [comment]
You need ask Icon pack developer for that.

**Comment by xmha97** [comment]
It's not a icon pack.
It's a feature from Android 13.
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

**Comment by deadlyjack** [comment]
Okay thank for letting me know.

**Comment by DevdouglasGfs** [comment]
I can help you with It @deadlyjack if you want

**Comment by xmha97** [comment]
> I can help you with It @deadlyjack if you want

Thanks 😊

**Comment by deadlyjack** [comment]
Sure, you are welcome to make PR. :)

**Comment by DevdouglasGfs** [comment]
I'm sorry, I've been doing a lot of work lately so I couldn't help @deadlyjack :(

**Comment by alMukaafih** [comment]
Is there anyone currently working on this?

**Comment by bajrangCoder** [comment]
https://github.com/Acode-Foundation/Acode/pull/1108
